# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Walli' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Walli
  pod 'Firebase'
  pod 'Firebase/Messaging'

  target 'WalliTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalliUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
